/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ManagedAccountsRouteImport } from './routes/managed-accounts'
import { Route as InternationalBrokingRouteImport } from './routes/international-broking'
import { Route as DiscretionaryInvestmentsRouteImport } from './routes/discretionary-investments'
import { Route as CorporateEnterpriseInvestmentsRouteImport } from './routes/corporate-enterprise-investments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagedAccountsRoute = ManagedAccountsRouteImport.update({
  id: '/managed-accounts',
  path: '/managed-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalBrokingRoute = InternationalBrokingRouteImport.update({
  id: '/international-broking',
  path: '/international-broking',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscretionaryInvestmentsRoute =
  DiscretionaryInvestmentsRouteImport.update({
    id: '/discretionary-investments',
    path: '/discretionary-investments',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateEnterpriseInvestmentsRoute =
  CorporateEnterpriseInvestmentsRouteImport.update({
    id: '/corporate-enterprise-investments',
    path: '/corporate-enterprise-investments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporate-enterprise-investments': typeof CorporateEnterpriseInvestmentsRoute
  '/discretionary-investments': typeof DiscretionaryInvestmentsRoute
  '/international-broking': typeof InternationalBrokingRoute
  '/managed-accounts': typeof ManagedAccountsRoute
  '/products': typeof ProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporate-enterprise-investments': typeof CorporateEnterpriseInvestmentsRoute
  '/discretionary-investments': typeof DiscretionaryInvestmentsRoute
  '/international-broking': typeof InternationalBrokingRoute
  '/managed-accounts': typeof ManagedAccountsRoute
  '/products': typeof ProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporate-enterprise-investments': typeof CorporateEnterpriseInvestmentsRoute
  '/discretionary-investments': typeof DiscretionaryInvestmentsRoute
  '/international-broking': typeof InternationalBrokingRoute
  '/managed-accounts': typeof ManagedAccountsRoute
  '/products': typeof ProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/corporate-enterprise-investments'
    | '/discretionary-investments'
    | '/international-broking'
    | '/managed-accounts'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/corporate-enterprise-investments'
    | '/discretionary-investments'
    | '/international-broking'
    | '/managed-accounts'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/corporate-enterprise-investments'
    | '/discretionary-investments'
    | '/international-broking'
    | '/managed-accounts'
    | '/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CorporateEnterpriseInvestmentsRoute: typeof CorporateEnterpriseInvestmentsRoute
  DiscretionaryInvestmentsRoute: typeof DiscretionaryInvestmentsRoute
  InternationalBrokingRoute: typeof InternationalBrokingRoute
  ManagedAccountsRoute: typeof ManagedAccountsRoute
  ProductsRoute: typeof ProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managed-accounts': {
      id: '/managed-accounts'
      path: '/managed-accounts'
      fullPath: '/managed-accounts'
      preLoaderRoute: typeof ManagedAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-broking': {
      id: '/international-broking'
      path: '/international-broking'
      fullPath: '/international-broking'
      preLoaderRoute: typeof InternationalBrokingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discretionary-investments': {
      id: '/discretionary-investments'
      path: '/discretionary-investments'
      fullPath: '/discretionary-investments'
      preLoaderRoute: typeof DiscretionaryInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-enterprise-investments': {
      id: '/corporate-enterprise-investments'
      path: '/corporate-enterprise-investments'
      fullPath: '/corporate-enterprise-investments'
      preLoaderRoute: typeof CorporateEnterpriseInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CorporateEnterpriseInvestmentsRoute: CorporateEnterpriseInvestmentsRoute,
  DiscretionaryInvestmentsRoute: DiscretionaryInvestmentsRoute,
  InternationalBrokingRoute: InternationalBrokingRoute,
  ManagedAccountsRoute: ManagedAccountsRoute,
  ProductsRoute: ProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
